import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ReactNode } from "react";
import { SidebarProvider } from "@/features/(main)/dashboard/sections/sidebar-section/sidebar-provider";
import DashboardHeader from "@/features/(main)/dashboard/sections/dashboard-header";
import SidebarSection from "@/features/(main)/dashboard/sections/sidebar-section/sidebar-section";
import CustomDialogLoadingProvider from "@/components/reusable-components/custom-dialog-loading/custom-dialog-loading-provider";
import ErrorBoundary from "@/components/reusable-components/error-boundary";
import ReactQueryProvider from "@/components/reusable-components/react-query-provider";
import { Toaster } from "@/components/ui/toaster";
import { SheetSidebarProvider } from "@/features/(main)/dashboard/components/sheet-sidebar/sheet-sidebar-provider";
import Row from "@/components/reusable-components/row";
import Column from "@/components/reusable-components/column";
import "./globals.css";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: [
            {
                url: "./icon.png",
                href: "./icon.png",
            },
        ],
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`h-screen w-screen overflow-hidden ${poppins.className}`}
            >
                <ReactQueryProvider>
                    <ErrorBoundary>
                        <SheetSidebarProvider>
                            <SidebarProvider>
                                <CustomDialogLoadingProvider>
                                    <div className="flex h-full w-full flex-row overflow-hidden">
                                        <SidebarSection />
                                        <Column className="h-full w-full flex-1">
                                            <DashboardHeader />
                                            {children}
                                        </Column>
                                    </div>
                                </CustomDialogLoadingProvider>
                            </SidebarProvider>
                        </SheetSidebarProvider>
                    </ErrorBoundary>
                </ReactQueryProvider>
                <Toaster />
            </body>
        </html>
    );
}
